name: Testing 
on:
  push:
    branches:
      - master

env:
  XDEBUG_MODE: coverage

jobs: 
  testing: 
    runs-on: ubuntu-22.04
    
    steps: 
      - name: Checkout Repo 
        uses: actions/checkout@v3
      
      - name: Update composer
        run: sudo composer self-update
      
      - name: Composer update
        run: composer update --no-interaction --prefer-dist
        
      - name: Run tests
        run:  vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
         



